# Control your input devices
# See https://wiki.hypr.land/Configuring/Variables/#input
input {
  accel_profile = flat
  kb_options = compose:caps # ,grp:alts_toggle
  numlock_by_default = true
  repeat_delay = 200
  repeat_rate = 50 # Change speed of keyboard repeat
  sensitivity = 0

  # Increase sensitity for mouse/trackpack (default: 0)
  # sensitivity = 0.35

  touchpad {
    natural_scroll = true # Use natural (inverse) scrolling
    clickfinger_behavior = true # Use two-finger clicks for right-click instead of lower-right corner
    disable_while_typing = true
    scroll_factor = 0.4
    tap-to-click = false
    tap-and-drag = false
  }
}

# Scroll faster in the terminal
windowrule = match:class (Alacritty|kitty), scroll_touchpad 1.5
windowrule = match:class com.mitchellh.ghostty, scroll_touchpad 0.2

# Enable touchpad gestures for changing workspaces
# See https://wiki.hyprland.org/Configuring/Gestures/
gesture = 3, horizontal, workspace

# Fix laggy cursor, and generally gesture = 3, horizontal, workspacehide it to prevent distractions
cursor {
  no_hardware_cursors = true
  inactive_timeout = 1.5
  hide_on_key_press = false
}



# Built-in keyboard only (match substring in `libinput list-devices` Name:)
# device:Microsoft Surface 045E:0C73 Keyboard {
