# Fix all dialogs in JetBrains products
windowrule = tag +jb, match:class ^jetbrains-.+$, match:float yes
windowrule = stay_focused on, match:tag jb
windowrule = no_initial_focus on, match:tag jb
windowrule = focus_on_activate on, match:class ^jetbrains-(?!toolbox)
# Center popups (except some context menus)
windowrule = move 30% 30%, match:class ^jetbrains-(?!toolbox), match:title negative:^win.*, match:float yes
windowrule = size 40% 40%, match:class ^jetbrains-(?!toolbox), match:title negative:^win.*, match:float yes
